fixes (#131)
* Use correct sha

* show matrix errors by failing the workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -78,10 +78,12 @@ jobs:
     concurrency: there-can-only-be-one
     if: ${{ always() }}
     steps:
-      - name: Harden Runner
-        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
-        with:
-          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
+      - name: Handle matrix error
+        run: |
+          if [[ "${{ needs.GatherCharacter.result }}" == "failure" ]]; then
+            echo "All matrix jobs failed."
+            exit 1
+          fi
 
       - name: Download artifact from build job
         uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
